version: "3"

## Search and replace 'express-docker-template' with the name of the service

services:
  express-docker-template:
    container_name: express-docker-template
    hostname: express-docker-template
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/bin
    build:
      context: .
    environment:
      - ENV
      - BUILD_VERSION=local-build # DO NOT SPECIFY WHEN DEPLOYING TO STAGE
      - NODE_ENV=${ENV} # CAN ONLY BE 'local' OR 'production', hardcode to 'production' WHEN DEPLOYING TO STAGE AND PROD
      - NODE_OPTIONS=--enable-source-maps
      - LOG_LEVEL=info
      - LOG_PRETTY=on
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
networks:
  default:
    name: special-projects
    external: true
