#!/bin/bash
#


# arr-health-check: Health check script for Sonarr/Radarr/Bazarr/Overseerr containers
# -------------------------------------------------------------------------------
# This script verifies basic health and optionally refreshes download clients if an API key is provided.
# It uses a lock file to prevent redundant checks and logs all output for debugging.
#
# - Logs all output to /scripts/$SERVICE_NAME-health-check.log
# - Uses a lock file to avoid redundant checks; lock file must be no more than 10 minutes old
# -------------------------------------------------------------------------------

# Determine the directory where this script is located
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Change to the script directory to ensure relative paths work
cd "$DIR"


# Source logging utility functions
source ./log_utils.sh

LOG_FILE="$DIR/$SERVICE_NAME-health-check.log"

# Log the current timestamp for traceability
log_msg "INFO" "Health check started for $SERVICE_NAME"

## Lock file logic: Only skip health check if a lock file exists and is 10 minutes old or younger.
# If a lock file exists and is 10 minutes old or younger, skip the health check to avoid spamming.
LOCK=$(find "$DIR" -iname "$SERVICE_NAME-health-check.lock" -mmin -10 | wc -l)

if [[ "$LOCK" != "0" ]]; then
    log_msg "WARN" "Qualifying lock file found. Skipping health check for $SERVICE_NAME."
    exit 0;
fi


# If an API key is provided, refresh download clients and indexers
if [[ "$API_KEY" != "" ]]; then
    log_msg "INFO" "API KEY DETECTED. Refreshing ${SERVICE_NAME} download clients."
    curl "http://localhost:${SERVICE_PORT}/${SERVICE_NAME}/api/v3/downloadclient/testall" \
        -X 'POST' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: en-US,en;q=0.9' \
        -H 'Content-Length: 0' \
        -H 'Content-Type: application/json' \
        -H "X-Api-Key: ${API_KEY}" \
        --compressed

    log_msg "INFO" "API KEY DETECTED. Refreshing ${SERVICE_NAME} indexers."
    curl "http://localhost:${SERVICE_PORT}/${SERVICE_NAME}/api/v3/indexer/testall" \
        -X 'POST' \
        -H 'Accept: application/json, text/javascript, */*; q=0.01' \
        -H 'Accept-Language: en-US,en;q=0.9' \
        -H 'Content-Length: 0' \
        -H 'Content-Type: application/json' \
        -H "X-Api-Key: ${API_KEY}" \
        --compressed
fi
log_msg "INFO" "All systems go for $SERVICE_NAME."
touch "$DIR/$SERVICE_NAME-health-check.lock"
exit 0;