#!/bin/bash
TIMESTAMP=$(date)

## URL TO THE VPN STATUS CHECK TO CONFIRM THIS CONTAINER IS GOING OUT TO THE INTERNET PROTECTED
VPN_STATUS_URL="https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data"

## CAPTURE STATUSES
VPN_STATUS=$(curl "$VPN_STATUS_URL");

echo "$TIMESTAMP" > /scripts/tmm-health-check.log
echo "VPN STATUS" >> /scripts/tmm-health-check.log
echo "$VPN_STATUS" | jq . >> /scripts/tmm-health-check.log

VPN_STATUS=$(echo "$VPN_STATUS" | jq .status)

## IF WE'RE NOT VPN PROTECTED, FAIL
if [[ "$VPN_STATUS" == null ]]; then
    echo "Not able to talk to DNS" >> /scripts/tmm-health-check.log
    exit 1;
else
    echo "VPN connected" >> /scripts/tmm-health-check.log
    exit 0;
fi